### ISSUE TITLE
dataset and setting

### ISSUE THREAD

**Issue by oDestroyeRo** [JasonZHM/CAEP#1]
I clone this repo and download BSD500 for the dataset when I run "train.py" the result  not a color image like this https://cdn1.imggmi.com/uploads/2019/5/30/53e33bf97ada5a4e1f39bc5f15c2c43b-full.png
Can you help me to slove the problem?

**Comment by haimengzhao** [comment]
Hi.
When you train a new model, the outputs are indeed colorless at first. But it will gradually change for the better as the training process goes on.
If you are willing to load the pretrained models, you will have to modify the settings in model.py to fit the selected checkpoint and change the path correspondingly in train.py.
